// <auto-generated />
using BookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookAPI.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20241027212945_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("BookAPI.Models.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            FirstName = "Jack",
                            LastName = "Author"
                        },
                        new
                        {
                            AuthorId = 2,
                            FirstName = "Sheila",
                            LastName = "Auteur"
                        },
                        new
                        {
                            AuthorId = 3,
                            FirstName = "Authmanda",
                            LastName = "Tor"
                        },
                        new
                        {
                            AuthorId = 4,
                            FirstName = "Authin",
                            LastName = "Eur"
                        });
                });

            modelBuilder.Entity("BookAPI.Models.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Description = "One for the ages.",
                            Title = "A Great Book",
                            Year = 2024
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            Description = "This one is not so great.",
                            Title = "A Great Book, part 2",
                            Year = 2024
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2,
                            Description = "A silly book indeed.",
                            Title = "A Silly Book",
                            Year = 2024
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 3,
                            Description = "So dense its stupidly briliant.",
                            Title = "Alpha et Omega al.",
                            Year = 2024
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
